#!/usr/bin/env python3
# ─────────────────────────────────────────────────────────
#  note_tool.py — note builder + quality gate
#
#  The model writes ONLY the note body (sections + evidence chain) to
#  <home>/src/<slug>.html. This tool wraps it into the full page and
#  keeps the library consistent — so skeleton HTML, the rail, the
#  catalog and the index are never hand-written or hand-maintained.
#
#    python3 note_tool.py build <slug> --title "Line one|Line two" \
#            --lede "…one <mark class=\"hl\">highlighted</mark> clause…" \
#            --lang zh-CN
#        assemble <home>/notes/<slug>.html from the body:
#        head + hero + auto-rail (derived from the section titles) +
#        related-notes rail + body + pager/colophon + script tag
#        (port from config.json), then update catalog.json and rebuild
#        index.html. Safe to re-run as sections grow (progressive
#        writing): the rail and index always match the body.
#
#    python3 note_tool.py lint <slug>
#        check the body+built page against the element quotas and
#        structural invariants; exit 1 with a report on any failure.
#
#  Paths: <home> defaults to ~/.understand (override with --home for
#  testing). Cross-platform Python 3.9+ stdlib only.
# ─────────────────────────────────────────────────────────
import argparse
import json
import re
import sys
import time
from pathlib import Path

DEFAULT_HOME = Path.home() / ".understand"

I18N = {
    "zh": {
        "rail_title": "本页小节",
        "related": "相关笔记",
        "all_notes": "全部笔记",
        "colophon2": "印刷友好 (⌘P) · 划选任意句子即可提问",
        "index_title": "你的笔记",
        "index_lede": "先讲给 5 岁的你，再回到工程现实。",
        "index_dir": "目录",
    },
    "en": {
        "rail_title": "ON THIS PAGE",
        "related": "Related notes",
        "all_notes": "All notes",
        "colophon2": "print-friendly (⌘P) · select any sentence to ask a follow-up",
        "index_title": "Your Notes",
        "index_lede": "Everything explained like you're five, then mapped back to engineering reality.",
        "index_dir": "Index",
    },
}

SECTION_RE = re.compile(r'<section[^>]*\bid="([^"]+)"[^>]*>.*?<h2>(.*?)</h2>', re.S)
NO_SPAN_RE = re.compile(r'<span class="no">[^<]*</span>')
TAG_RE = re.compile(r"<[^>]+>")


def t(lang):
    return I18N["zh" if lang.lower().startswith("zh") else "en"]


def esc(s):
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def plain(s):
    return TAG_RE.sub("", NO_SPAN_RE.sub("", s)).strip()


def load_json(path, default):
    try:
        return json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return default


def save_json(path, obj):
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with Path(path).open("w", encoding="utf-8", newline="\n") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
        f.write("\n")


def parse_sections(body):
    secs = []
    for sid, h2 in SECTION_RE.findall(body):
        secs.append((sid, plain(h2)))
    return secs


def port_of(home):
    cfg = load_json(home / "config.json", {})
    return cfg.get("port", 8899)


def rail_html(secs, lang, catalog, slug, date):
    T = t(lang)
    lis = "".join(
        '    <li%s><a href="#%s">%s</a></li>\n' % (
            ' class="here"' if i == len(secs) - 1 else "",
            sid,
            esc(title),
        )
        for i, (sid, title) in enumerate(secs)
    )
    related = sorted(
        (e for k, e in catalog.items() if k != slug),
        key=lambda e: e.get("date", ""),
        reverse=True,
    )[:3]
    rel = ""
    if related:
        rel += "    <p><b>%s</b></p>\n" % esc(T["related"])
        for e in related:
            rel += '    <p><a href="%s.html">%s</a></p>\n' % (esc(e.get("slug", "")), esc(e.get("title", "")))
    rel += '    <p><a href="index.html">→ %s</a></p>\n' % esc(T["all_notes"])
    return (
        '<nav class="rail" aria-label="%s">\n'
        '  <p class="rail-brand"><a href="index.html">Help Me Understand</a></p>\n'
        '  <p class="rail-sub">annotated textbook<br>%s</p>\n'
        '  <p class="rail-title">%s</p>\n'
        "  <ol>\n%s  </ol>\n"
        '  <div class="rail-meta">\n%s  </div>\n'
        "</nav>\n"
    ) % (esc(T["rail_title"]), esc(date), esc(T["rail_title"]), lis, rel)


def page_html(slug, body, title, lede, lang, date, port, rail):
    T = t(lang)
    title_lines = "<br>".join(esc(x.strip()) for x in title.split("|") if x.strip())
    flat_title = " ".join(plain(x) for x in title.split("|")).strip()
    return (
        '<!DOCTYPE html>\n'
        '<!-- Help Me Understand · note: %s (generated by note_tool.py — '
        "edit the body in src/%s.html and rebuild, not this file) -->\n"
        '<html lang="%s">\n'
        "<head>\n"
        '<meta charset="UTF-8">\n'
        '<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>%s · Help Me Understand</title>\n"
        '<link rel="stylesheet" href="assets/style.css">\n'
        '<link rel="stylesheet" href="assets/qa.css">\n'
        "</head>\n"
        "<body>\n\n"
        "%s"
        '<main class="main">\n'
        '  <div class="content">\n\n'
        '    <header class="hero">\n'
        '      <p class="eyebrow">Help Me Understand<span class="sep">/</span>%s<span class="sep">/</span>topic</p>\n'
        '      <h1 class="chapter">%s</h1>\n'
        '      <p class="lede">%s</p>\n'
        '      <div class="hero-rule"></div>\n'
        "    </header>\n\n"
        "%s\n"
        '    <footer class="pager">\n'
        '      <a href="index.html"><span class="dir">← %s</span><span class="t">%s</span></a>\n'
        '      <a class="next" href="index.html"><span class="dir">%s →</span><span class="t">%s</span></a>\n'
        "    </footer>\n\n"
        '    <footer class="colophon">\n'
        "      %s · generated by Help Me Understand · %s<br>\n"
        "      %s\n"
        "    </footer>\n\n"
        "  </div>\n"
        "</main>\n"
        '<script defer src="assets/interactive.js" data-port="%s"></script>\n'
        "</body>\n"
        "</html>\n"
    ) % (
        esc(slug), esc(slug), esc(lang), esc(flat_title),
        rail,
        esc(date), title_lines, lede,
        body,
        esc(T["index_dir"]), esc(T["all_notes"]), esc(T["index_dir"]), esc(T["all_notes"]),
        esc(flat_title), esc(date), esc(T["colophon2"]),
        esc(str(port)),
    )


def index_html(catalog, lang, date):
    T = t(lang)
    cards = ""
    for slug, e in sorted(catalog.items(), key=lambda kv: kv[1].get("date", ""), reverse=True):
        cards += (
            '      <a class="toc-card" href="%s.html">\n'
            "        <span class=\"no\">%s</span>\n"
            "        <span class=\"t\">%s</span>\n"
            "        <span class=\"d\">%s</span>\n"
            "      </a>\n"
        ) % (esc(slug), esc(e.get("date", "")), esc(e.get("title", "")), esc(e.get("lede", "")))
    return (
        '<!DOCTYPE html>\n<html lang="%s">\n<head>\n'
        '<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1">\n'
        "<title>%s · Help Me Understand</title>\n"
        '<link rel="stylesheet" href="assets/style.css">\n'
        '<link rel="stylesheet" href="assets/qa.css">\n'
        "</head>\n<body>\n"
        '<main class="main">\n  <div class="content">\n\n'
        '    <header class="hero">\n'
        '      <p class="eyebrow">Help Me Understand<span class="sep">/</span>%s<span class="sep">/</span>index</p>\n'
        '      <h1 class="chapter">%s</h1>\n'
        '      <p class="lede">%s</p>\n'
        '      <div class="hero-rule"></div>\n'
        "    </header>\n\n"
        '    <div class="toc-cards">\n%s    </div>\n\n'
        '    <footer class="colophon">\n'
        "      generated by Help Me Understand · %s<br>\n"
        "      %s\n"
        "    </footer>\n\n"
        "  </div>\n</main>\n"
        '<script defer src="assets/interactive.js"></script>\n'
        "</body>\n</html>\n"
    ) % (esc(lang), esc(T["index_title"]), esc(date), esc(T["index_title"]), esc(T["index_lede"]), cards, esc(date), esc(T["colophon2"]))


def cmd_build(args):
    home = Path(args.home).expanduser()
    src = home / "src" / (args.slug + ".html")
    if not src.exists():
        print("body not found: %s — write it first (see body-template.html)" % src, file=sys.stderr)
        sys.exit(1)
    body = src.read_text(encoding="utf-8")
    secs = parse_sections(body)
    if not secs:
        print("no <section> blocks with id= found in the body", file=sys.stderr)
        sys.exit(1)
    if not args.title or not args.lede:
        print("--title and --lede are required", file=sys.stderr)
        sys.exit(1)

    date = args.date or time.strftime("%Y-%m-%d")
    catalog = load_json(home / "catalog.json", {})
    port = port_of(home)
    lang = args.lang or "en"

    rail = rail_html(secs, lang, catalog, args.slug, date)
    html = page_html(args.slug, body, args.title, args.lede, lang, date, port, rail)
    notes = home / "notes"
    notes.mkdir(parents=True, exist_ok=True)
    (notes / (args.slug + ".html")).write_text(html, encoding="utf-8", newline="\n")

    catalog[args.slug] = {
        "slug": args.slug,
        "title": " ".join(plain(x) for x in args.title.split("|")).strip(),
        "lede": plain(args.lede),
        "date": date,
        "lang": lang,
    }
    save_json(home / "catalog.json", catalog)
    (notes / "index.html").write_text(index_html(catalog, lang, date), encoding="utf-8", newline="\n")

    out = {
        "ok": True,
        "note": str(notes / (args.slug + ".html")),
        "sections": len(secs),
        "rail": [s[1] for s in secs],
        "url": "http://127.0.0.1:%d/%s.html" % (port, args.slug),
        "catalog": len(catalog),
    }
    print(json.dumps(out, ensure_ascii=False))


def count(pattern, text):
    return len(re.findall(pattern, text))


def cmd_lint(args):
    home = Path(args.home).expanduser()
    src = home / "src" / (args.slug + ".html")
    built = home / "notes" / (args.slug + ".html")
    for path in (src, built):
        if not path.exists():
            print("FAIL missing file: %s" % path)
            sys.exit(1)
    body = src.read_text(encoding="utf-8")
    page = built.read_text(encoding="utf-8")

    checks = []

    def ck(name, ok, detail=""):
        checks.append((ok, name + ((" — " + detail) if detail and not ok else "")))

    secs = parse_sections(body)
    ck("≥5 sections", len(secs) >= 5, "%d" % len(secs))
    eli5 = count(r'class="eli5"', body)
    ck("eli5 box in every section", eli5 >= len(secs), "%d boxes / %d sections" % (eli5, len(secs)))
    toys = count(r'class="toys"', body)
    ck("≥4 toys per eli5 box", toys >= 4 * eli5, "%d toys / %d boxes" % (toys, eli5))
    ck("≥1 SVG diagram", count(r'figure class="diag"', body) >= 1)
    ck("≥2 tables", count(r"<table", body) >= 2)
    ck("≥1 trace block", count(r'class="trace"', body) >= 1)
    ck("≥2 deep dives (h3)", count(r"<h3>", body) >= 2)
    ck("≥2 callouts", count(r'class="callout', body) >= 2)
    ck("≥3 evidence items", count(r"<li id=", body) >= 3)
    hl = count(r'class="hl"', page)
    ck("≥2 highlighter marks (body+lede)", hl >= 2, "%d" % hl)

    ids = {s[0] for s in secs}
    ck("unique section ids", len(ids) == len(secs))
    ids |= set(re.findall(r'id="([^"]+)"', body))  # evidence-chain anchors count too
    hrefs = re.findall(r'href="#([^"]+)"', page)
    ck("rail anchors resolve", all(h in ids for h in hrefs),
       ",".join(h for h in hrefs if h not in ids))
    ck("no refs outside served dir", "../" not in page)
    missing_assets = [
        m for m in re.findall(r'(?:href|src)="(assets/[^"]+)"', page)
        if not (home / "notes" / m).exists()
    ]
    ck("asset files exist", not missing_assets, ",".join(missing_assets))
    ck("lang attribute set", re.search(r'<html lang="[^"]+"', page) is not None)

    fails = [c for c in checks if not c[0]]
    for ok, name in checks:
        print("%s %s" % ("✔" if ok else "✘", name))
    if fails:
        print("LINT FAILED (%d)" % len(fails))
        sys.exit(1)
    print("LINT PASSED")


def main():
    ap = argparse.ArgumentParser(description="Help Me Understand note builder + quality gate")
    ap.add_argument("--home", default=str(DEFAULT_HOME), help="root directory (default: ~/.understand)")
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("build", help="assemble the page from the body, update catalog + index")
    b.add_argument("slug")
    b.add_argument("--title", required=True, help='note title; "|" splits the two hero lines')
    b.add_argument("--lede", required=True, help="one-sentence takeaway; may contain one <mark class=\"hl\"> clause")
    b.add_argument("--lang", default="en")
    b.add_argument("--date", default=None)
    l = sub.add_parser("lint", help="check quotas + structural invariants")
    l.add_argument("slug")
    args = ap.parse_args()

    if args.cmd == "build":
        cmd_build(args)
    elif args.cmd == "lint":
        cmd_lint(args)


if __name__ == "__main__":
    main()
